language: java
jdk: oraclejdk8
sudo: false

cache:
  directories:
  - "$HOME/.m2"

jobs:
  include:
  - stage: test
    script: mvn test
  - stage: build
    script: mvn build -DskipTests=true

branches:
  only:
  - master